### ISSUE TITLE
lex-bot-get-schema not working

### ISSUE THREAD

**Issue by AlFalahTaieb** [aws-samples/amazon-lex-bot-deploy#1] opened 2019-09-26 13:13 UTC
* amazon-lex-bot-deploy version:  **0.1.10** 
* Python version: 3.6.8
* Operating System: Ubuntu 18.04.2 LTS

### Description
I installed the amazon-lex-bot-deploy, i'm trying to run it, the problem i'm facing, is that i'm always getting an error related to lex-bot-got-schema. 
### What I Did
I called both lex_bot_deploy & lex-bot-get-schema but unfortunately i'm having problem with the second command. 
```
sh : lex-bot-get-schema: not found
```

**Comment by schadem** [comment] 2019-09-27 21:18
let me check

**Comment by schadem** [comment] 2019-09-27 21:39
Can you share the commands you used to install to let me reproduce?

This is the sequence I just used for testing and it worked fine.

```
sudo apt update
sudo apt install -y python3-pip
python3 -m pip install pip --upgrade
python3 -m pip install --user amazon-lex-bot-deploy
export PATH=$PATH:~/.local/bin/
lex-bot-deploy
lex-bot-get-schema
```

Used a t2.nano with AMI 'ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20190722.1 (ami-07d0cf3af28718ef8)'

**Comment by schadem** [comment] 2019-10-08 21:05
Closing because no further information does not allow to analyze.
Please reopen if issue persists.

**Closed by schadem** 2019-10-08 21:05 UTC
